### ISSUE TITLE
For Some svg's font generated is not right

### ISSUE THREAD

**Issue by veereshmeesala** [nfroidure/gulp-iconfont#136] opened 2016-12-22 16:31 UTC
Hi,

For few svgs the icon font generated is not the intended output, please let me know me if i to have amend the svg or my gulp configuration.

**My Gulp config is as follows** 
gulp.task(assets.createIconFontsFromSvg, function () {
 return gulp.src(config.images.svgFontIconsSourceFiles + "/*.svg")
         .pipe(iconfont({
             fontName: "iconfont",
             formats: ["ttf", "eot", "woff", "svg"],
             appendCodepoints: true,
             appendUnicode: false,
             normalize: true,
             fontHeight: 1001,
             centerHorizontally: true
         }))
         .on("glyphs", function (glyphs, options) {
             gulp.src(config.images.svgFontIconsSourceFiles + "/icons.scss")
             .pipe(consolidate("underscore", {
             glyphs: glyphs,
             fontName: options.fontName,
             fontDate: runTimestamp
         }))
            .pipe(gulp.dest(config.images.svgFontIconStagingDir));
         })
            .pipe(gulp.dest(config.images.svgFontIconStagingDir));
 });

my Svg which is not rendered 
[https://gist.github.com/veereshmeesala/6e5c42e9bec8878836618e8ccb1df117](url)

[Horizontal-Line.zip](https://github.com/nfroidure/gulp-iconfont/files/669242/Horizontal-Line.zip)

Thanks in advance
Veeresh

**Comment by klojniewski** [comment] 2017-02-06 08:22
Any updates? I have the same problem.

**Comment by bm2u** [comment] 2017-03-02 12:45
@Veeresh: Hi, what format is the source file? Try to reduce groups and layers to one element and retry, please.

**Comment by hiyangguo** [comment] 2017-03-17 02:30
I have the same problem too.It look like the same to this.
I hope result.
![image](https://cloud.githubusercontent.com/assets/15609339/24026461/435b5dd2-0afc-11e7-94a1-30d9deb718b6.png)
Now result.
![image](https://cloud.githubusercontent.com/assets/15609339/24026496/8162f086-0afc-11e7-9dde-167ca57e0d5c.png)
This is my [gulp file](https://github.com/rsuite/rsuite-icon-font/blob/master/gulpfile.js).

**Comment by nfroidure** [comment] 2017-03-17 07:49
Did you try https://github.com/nfroidure/gulp-iconfont/issues/138 ?

**Comment by hiyangguo** [comment] 2017-03-27 09:31
My problem is resolve , thx @nfroidure . 😁

**Comment by bm2u** [comment] 2017-03-27 10:31
@hiyangguo: would be interesting, how you resolved it. Thx

**Comment by hiyangguo** [comment] 2017-03-27 10:38
@bm2u  Add this confing in options
```javascript
 fontHeight: 1001, normalize:true
```

This is my [gulpfile](https://github.com/rsuite/rsuite-icon-font/blob/master/gulpfile.js#L16)

reference  https://github.com/nfroidure/gulp-iconfont/issues/138

**Comment by aseem2625** [comment] 2017-07-11 13:55
@hiyangguo This didn't answer the original answer. He already has `fontHeight: 1001` and `normalize: true`

I'm also facing same issue even after adding those 2 options.

**Comment by nfroidure** [comment] 2017-07-15 16:09
@aseem2625 not related to your issue. Closing since very old and probably a duplicate of: https://github.com/nfroidure/gulp-iconfont/issues/143

**Closed by nfroidure** 2017-07-15 16:09 UTC
