### ISSUE TITLE
Error: Checksum error in glyf

### ISSUE THREAD

**Issue by c-wei** [nfroidure/gulp-iconfont#48] opened 2015-05-30 04:52 UTC
Hi, i was trying to get my gulp-iconfont up and running with by following the given instructions it doesn't generate any output even it says "font created". And it gave be the error message and details below.

### Operating system:
Windows 8.1
### NPM version:
1.3.11
### Compiling shell:
 Git Bash

#### Error Message:
```
[14:25:33] gulp-svgicons2svgfont: Font created

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Checksum error in glyf
```
#### Folder structure:
```
project
- app 
  - fonts (font generated output destination)
- assets
  - icons (*.svg icons sits inside this folder)
- node_modules
- .gulpfile.js
- package.json
```
#### package.json
```json
{
"devDependencies": {
    "gulp": "^3.8.5",
    "gulp-load-plugins": "^0.8.0",
    "gulp-iconfont": "",
    "gulp-iconfont-css": ""
  },
  "engines": {
    "node": ">=0.10.0"
  },
  "private": true
}
```
#### gulpfile.js
```javascript
'use strict';

var gulp = require('gulp');
var $ = require('gulp-load-plugins')();

// Generate Icon Font
gulp.task('iconfont', function(){
    gulp.src(['assets/icons/*.svg'])
    .pipe($.iconfont({
      fontName: 'icons',
      normalize: true,
      fontHeight: 1000
     }))
    .pipe(gulp.dest('app/fonts/'));
});

gulp.task('default', function() {
	gulp.start('iconfont');
});	
```

**Comment by kuon** [comment] 2015-06-04 14:08
I have the same issue.

**Comment by nfroidure** [comment] 2015-06-04 15:20
Please provide the full stack trace for the "Error: Checksum error in glyf" error.

Also, could you remove the icons progressively until you got the one that causes the error and share it with us?

**Comment by kuon** [comment] 2015-06-04 16:17
```
$ gulp iconFont
[15:52:12] Using gulpfile ./gulpfile.js
[15:52:12] Starting 'iconFont'...
[15:52:12] gulp-svgicons2svgfont: Font created

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Checksum error in glyf
```

Unfortunately I cannot reproduce the error now. I made some changes in the icons and it now works.

If it happens again I'll be sure to share the svg causing the error.

**Comment by nfroidure** [comment] 2015-06-15 14:09
Closing since no issue anymore. Feel free to reopen if the problem remains.

**Closed by nfroidure** 2015-06-15 14:09 UTC

**Comment by stephancom** [comment] 2015-08-09 00:52
I had this issue too, with a batch of SVG's from Illustrator.  I figured out through trial and error - at least I think so, because I haven't finished yet - that to make it work I needed to remove these attributes from the \<svg\> tag:

```
xmlns:x="&ns_extend;" xmlns:i="&ns_ai;" xmlns:graph="&ns_graphs;"
```

and also remove the \<foreignObject\> tag

```
	<foreignObject requiredExtensions="&ns_ai;" x="0" y="0" width="1" height="1">
		<i:pgfRef  xlink:href="#adobe_illustrator_pgf">
		</i:pgfRef>
	</foreignObject>
```

I also took out the <!DOCTYPE> and <!ENTITY> tags - I guessed at all this from comparing to some SVG's that were known to work and were missing these things.  Maybe I'm taking out more than I need to, or maybe this is insufficient, but my partial results so far indicate this is what was needed for me.

**Comment by wookoouk** [comment] 2016-08-18 20:56
worked fine on OSX, not working on Windows 7 or Ubuntu (Linux 4.5.5-x86_64)

/opt/dyecons/node_modules/gulp-iconfont/node_modules/gulp-ttf2woff2/node_modules/ttf2woff2/jssrc/ttf2woff2.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](f
Error: Checksum error in glyf

**Comment by xxholly32** [comment] 2016-11-23 09:12
@wookoouk i have a same error. not working on Windows 7. can we just not use W7 or gulp-svgmin ? or better idea?

**Comment by wookoouk** [comment] 2016-11-23 09:49
@xxholly32 I gave up in the end. I was working on my own icon font because I couldn't find one that suited me, but then I found simplelineicons.com and stuck with that for my projects.

**Comment by xxholly32** [comment] 2016-11-24 08:50
@wookoouk @nfroidure 
finally i find the problem
the ttf file form gulp task iconfont is different to the ttf file form the svg2ttf commond.
it leads to ttf2woff`s problem, because ttf file is miss many codes.

the result of gulp-svg2tff alaways have 91 line codes.
my demo [https://github.com/xxholly32/startNodejs/tree/gh-pages/demo/iconfont-svg-demo](https://github.com/xxholly32/startNodejs/tree/gh-pages/demo/iconfont-svg-demo)
