### ISSUE TITLE
The appendUnicode option duplicates the codepoints

### ISSUE THREAD

**Issue by nesk** [nfroidure/gulp-iconfont#53] opened 2015-06-18 10:23 UTC
If I use the `appendUnicode: true` option, all my SVG filenames are prepended with the `uEA01-` string. Before the v2 I always had a unique codepoint for each of my files.

Am I missing something?

**Comment by nesk** [comment] 2015-06-18 12:50
More details! If I process a first batch of files like this:

```
icon1.svg
icon2.svg
```

I will get:

```
uEA01-icon1.svg
uEA02-icon2.svg
```

I then I add two new files, I will go from this:

```
uEA01-icon1.svg
uEA02-icon2.svg
icon3.svg
icon4.svg
```

to this:

```
uEA01-icon1.svg
uEA02-icon2.svg
uEA01-icon3.svg
uEA02-icon4.svg
```

**Comment by nfroidure** [comment] 2015-06-19 07:07
That's a bug. Feel free to PR a fix, ideally with tests reproducing the problem otherwise i'll try to have a look when possible to fix it.

**Comment by nfroidure** [comment] 2015-06-20 16:21
The bug should now be fixed by switching to 3.0.0. Feel free to reopen if you the problem persist.

**Comment by nesk** [comment] 2015-06-20 16:24
Amazing! Thank you for being so fast!

**Comment by geoRG77** [comment] 2015-06-24 08:58
Is it really fixed? I'm still getting `Error: The unicode codepoint of the glyph check seems to be already used by another glyph.`. Thanks!

**Comment by nfroidure** [comment] 2015-06-24 09:09
Did you renamed duplicated icons codepoints in filenames?

**Comment by geoRG77** [comment] 2015-06-24 09:33
No, I added a new SVG and then run the gulp task... the new SVG now has same codepoint:
`uEA01-check.svg` and `uEA01-money`

**Comment by nfroidure** [comment] 2015-06-24 09:50
Reopening, i'll have a look at it. Did you forget the .svg ext for the money icon or is it the actual filename?

**Comment by nfroidure** [comment] 2015-06-24 09:52
Also, can you double check if one is UE001 and the other UEA01 since the startcodepoint changed it may have mistaken you.

**Comment by geoRG77** [comment] 2015-06-24 10:53
I forgot the extension, sorry. I copied the name, see attached screenshot.

![screen shot 2015-06-24 at 12 52 46](https://cloud.githubusercontent.com/assets/735057/8328306/fe54a398-1a6f-11e5-9218-8e537b06e6fd.png)

**Comment by nfroidure** [comment] 2015-06-27 06:59
Sadly i can't reproduce the error https://github.com/nfroidure/svgicons2svgfont/blob/master/tests/metadata.mocha.js#L155

I'll try to reproduce it at the icon directory level.

**Comment by nfroidure** [comment] 2015-06-27 08:03
Also added tests to the file sorting functions on with the metadata provider is built and till no way to reproduce it https://github.com/nfroidure/svgicons2svgfont/commit/99730d0cdb3c2f3339a39c3ac7251f125e40b33e

@nesk do you still have the issue?

**Comment by nfroidure** [comment] 2015-06-27 08:04
@geoRG77 did you updated to the last version?

**Comment by nfroidure** [comment] 2015-07-05 08:05
Can't reproduce. Closing.

**Closed by nfroidure** 2015-07-05 08:05 UTC
Labels: bug
