### ISSUE TITLE
Glyph Vertical Offset In Windows Browsers

### ISSUE THREAD

**Issue by Undistraction** [nfroidure/gulp-iconfont#100] opened 2015-12-30 14:51 UTC
I appreciate that this might be caused by one of the libs you use, but I'm seeing issues with vertical alignment of glyphs in browsers on Windows (IE10, IE11, Chrome) across all font file types.

I have set up a codepen here: http://codepen.io/Pedr/pen/eJBLZM

Compare display of icons in Chrome 47.0.2526.106 (64-bit) OSX:

![chrome-osx](https://cloud.githubusercontent.com/assets/161489/12052224/9f52fdb6-af04-11e5-94d5-0db87c79c452.jpg)

With Chrome 47.0.2526.106 Windows:

![chrome windows](https://cloud.githubusercontent.com/assets/161489/12052230/b2506796-af04-11e5-929b-098e2ab6f268.jpg)

My gulpfile:

```
var gulp = require('gulp');
var iconfont = require('gulp-iconfont');
var consolidate = require('gulp-consolidate');
var rename = require('gulp-rename');

var fontName = 'AppIcons';

gulp.task('appIconFont', function(){
  return gulp.src(['./graphic-source/fonts/app-icon-font/svg/*.svg'])
    .pipe(iconfont({
      fontName: fontName,
      // Normalize icon sizes
      fontHeight: 512, // Height of the SVG files
      normalize: true,
      formats: ['woff2', 'woff']
    }))
    .on('glyphs', function(glyphs, options) {
      gulp.src('./templates/sass/_app-icon-font.template.scss')
        .pipe(consolidate('lodash', {
          glyphs: glyphs,
          fontName: fontName,
          fontPath: './src/fonts/app-icon-font',
          className: 'ai'
        }))
        .pipe(rename('_app.assets.fonts.app-icons.scss'))
        .pipe(gulp.dest('./src/sass/assets/fonts'));
    })
    .pipe(gulp.dest('./src/fonts/app-icon-font'));
});
```

Example of source SVG:

[Icons.zip](https://github.com/nfroidure/gulp-iconfont/files/74920/Icons.zip)

**Comment by lokywin** [comment] 2015-12-30 17:26
![screen shot 2015-12-30 at 9 22 45 am](https://cloud.githubusercontent.com/assets/545713/12054279/0ac5ecbc-aed7-11e5-9048-9df525f7fb39.png)
The left panel is Chrome on Mac, and the right one is Chrome on Windows. Both chrome versions are  47.0.2526.106.
The icons look slight different because of antialias, but their position appear the same in my case.

**Comment by lokywin** [comment] 2015-12-30 17:31
BTW, I see you use woff2 in the example. I am using woff, so I am wondering if the format could be the cause here. I read some where in the doc, awhile back, that there was some issues with woff2.

**Comment by nickelleon** [comment] 2016-01-06 19:48
+1

The glyphs are below the intended area by ~40% in my project. I have tried every CSS technique I know of, but I don't understand the root problem, so its like shooting in the dark. After spending a day and a half trying to make it work, I finally threw my hands up and went to see if there were any open issues for this project. I'm glad that I'm not going insane because someone else is having the exact same issue! A little guidance would be great here if anyone has it.

**Comment by Undistraction** [comment] 2016-01-06 21:34
Sorry for not replying sooner. Turned out it was an issue with the svg
files. Their x/y and viewbox were not 0/0. This caused issues in Windows
browsers. It is a well known issue with svgs authored using Illustrator.
The very latest version of Illustrator CC fixes this issue, but doesn't fix
it for files authored from a previous version of Illustrator. You will need
to open each .svg file in Illustrator and move the art back to a 0/0
position (the artwork will be off the artboard somewhere). Hope that helps.

**Comment by nickelleon** [comment] 2016-01-08 14:46
Thank you very much for the explanation! I was able to resolve the issue too by optimizing my SVGs. There was some dormant code in one of the SVGs that caused all of my glyphs to be off (in Windows browsers only) like the original post. Thank you!

**Comment by nfroidure** [comment] 2016-01-08 15:04
Closing the issue, feel free to PR the README if you think it is necessary.

**Closed by nfroidure** 2016-01-08 15:04 UTC
Labels: question

**Comment by Vargentum** [comment] 2016-01-18 17:14
@nickelleon can you describe the list of SVG optimizations, that you've provided for your files? 
Are they present in a [a list](https://github.com/svg/svgo#what-it-can-do) of svgo optimizer plugins?

**Comment by nickelleon** [comment] 2016-01-26 18:44
@Vargentum , I manually bisected my list of SVGs until I identified the SVG that was causing the misalignment. After that, I opened the SVG in my editor and noticed a lot of redundant code. I removed the redundant code bit by bit to see if it affected the shape of the icon. Once I was done removing the redundant code, and noticing no change to the shape, the font family generated correctly.

**Comment by mattgreenfield** [comment] 2016-09-16 15:54
I was having this exact problem and can confirm that optimising the SVGs using the [svgo](https://github.com/svg/svgo#how-to-use) fixed it. Although be careful as some of the detail in my SVG's was removed.

Thanks for the the help.
