### ISSUE TITLE
Nothing is generated at some computers

### ISSUE THREAD

**Issue by JoeZheng2015** [nfroidure/gulp-iconfont#104] opened 2016-01-05 08:37 UTC
Hi, nfroidure. I use gulp-iconfont in a computer which the operating system is Windows 7 and it works correctly. But I clone  the repository in another computer which the operating system is also Windows 7 but it generate nothing after the task. In addition, both of them have the same version of nodejs, npm and gulp. I notice that OSX has the same problem.

**Comment by nfroidure** [comment] 2016-01-05 14:08
Can't help with such a vague description.

Please provide more informations like:
NPM install output, npm version, node version, inputted SVG icons or event better a test case in order to reproduce the bug you're encountering.

**Comment by nfroidure** [comment] 2016-01-14 11:28
Closing since no news.

**Closed by nfroidure** 2016-01-14 11:28 UTC
Labels: invalid
