### ISSUE TITLE
Error!help me

### ISSUE THREAD

**Issue by guohuihot** [nfroidure/gulp-iconfont#103] opened 2016-01-04 02:28 UTC
![qq](https://cloud.githubusercontent.com/assets/3119995/12082346/33b1ed94-b2cc-11e5-913a-17361fe19a73.png)

**Comment by nfroidure** [comment] 2016-01-04 08:25
Please provide me the inputted TTF font.

**Comment by nfroidure** [comment] 2016-01-04 08:25
Closing this issue since it is a duplicate of https://github.com/nfroidure/ttf2woff2/issues/23

**Closed by nfroidure** 2016-01-04 08:25 UTC
Labels: invalid
