### ISSUE TITLE
SVG Icons seem to be destroyed after building the font with gulp-iconfont

### ISSUE THREAD

**Issue by julkuh** [nfroidure/gulp-iconfont#139] opened 2017-03-04 09:04 UTC
Hey there,

i've just created some nice looking svg's and let gulp-iconfont build a webfont out of them. But in the webfonts, the glyps look realy destructed and compressed. Is there a limit of Anchorpoints per glyph or anything like that which could cause the problem?

Here are two images:

The first one is the result building the font with icommon.io:
![image](https://cloud.githubusercontent.com/assets/10866537/23577531/e4cd4cd8-00c1-11e7-88c4-a580d1b1d290.png)

The second shows the result when bulding the font with gulp-iconfont
![image](https://cloud.githubusercontent.com/assets/10866537/23577534/fd05328e-00c1-11e7-92d3-6db3eb187f4b.png)

**Comment by pete-hotchkiss** [comment] 2017-03-07 14:44
I get similar

![image](https://cloud.githubusercontent.com/assets/16895748/23661373/751d1da2-0344-11e7-907a-2d40a3ccf55d.png)
is the SVG file

![image](https://cloud.githubusercontent.com/assets/16895748/23661378/7f303464-0344-11e7-830d-0d3df8a4b1da.png)
 is the resulting font

**Comment by nfroidure** [comment] 2017-03-07 15:10
Duplicate of https://github.com/nfroidure/gulp-iconfont/issues/138 ?

**Comment by julkuh** [comment] 2017-03-07 15:11
I found out that you can set the property `fontSize:1000`. Then it looks already much nicer

```
iconfont({
      fontName: 'myfont', // required 
      prependUnicode: true, // recommended option 
      formats: ['ttf', 'eot', 'woff'], // default, 'woff2' and 'svg' are available 
      fontSize: 1000
    })
```

**Comment by nfroidure** [comment] 2017-03-07 15:15
Great. Closing.

**Closed by nfroidure** 2017-03-07 15:15 UTC
