### ISSUE TITLE
appendUnicode - duplicate unicode codepoin

### ISSUE THREAD

**Issue by pinin** [nfroidure/gulp-iconfont#72] opened 2015-07-30 16:51 UTC
Hello, can you advise me how to solve this problem.
Peformance - appendUnicode: true,

first compilation - ok
If you add new svg symbols into the source folder, an error occurs - duplicate unicode codepoint is added to the name.

thank you

**Comment by nfroidure** [comment] 2015-07-30 17:50
By updating your gulp-iconfont version to the last one, you should get rid of this problem https://github.com/nfroidure/gulp-iconfont/issues/67

**Comment by pinin** [comment] 2015-07-30 19:40
Thank you for the quick response,
Unfortunately for me, it still does not work with the latest version.

Are there any dependencies for Windows?

**Comment by nfroidure** [comment] 2015-07-31 06:26
Can you for the gulp-svgiconstosvgfont project and run its tests from your setup?

Wondering if it isn't related to the Windows case insensitive handling of pathes.

**Comment by pinin** [comment] 2015-07-31 10:26
Greetings,
I do not know exactly what you mean, but if you start gulp-svgicons2svgfont with my setup so everything runs well.
If appendUnicode: false - everything ok - svg files have a unique Unicode
If appendUnicode: true - error - duplicate Unicode

**Comment by pinin** [comment] 2015-07-31 11:13
One thing is
default:
calendar.svg
calendar-alert.svg
calendar-agenda.svg

I start the task - files are renamed
uEA01-calendar-agenda.svg
uEA02-calendar-alert.svg
uEA03-calendar.svg

Transcripts on hand
UEA01-calendar-agenda.svg
UEA02-calendar-alert.svg
UEA03-calendar.svg

Add more files
bookmark.svg
bookmark-o.svg
bookmark-favorite.svg
UEA01-calendar-agenda.svg
UEA02-calendar-alert.svg
UEA03-calendar.svg

I run a task
UEA01-calendar-agenda.svg
UEA02-calendar-alert.svg
UEA03-calendar.svg
uEA04-bookmark-favorite.svg
uEA05-bookmark-o.svg
uEA06-bookmark.svg

This works well - not only on alphabetical order, but the task will be OK
Something is wrong - capital or small letters

**Comment by nfroidure** [comment] 2015-07-31 17:01
It seems impossible since the test i just created proves the files come in the metadataProvider in the suitable order.

Can you check the gulp-iconfont version you're using in your package.json file and put it here?

**Comment by nfroidure** [comment] 2015-07-31 17:09
Added more tests but no problem again. Please adapt this test and PR the project to reproduce the bug. https://github.com/nfroidure/gulp-svgicons2svgfont/blob/master/tests/tests.mocha.js#L351-L406

Closing in the meanwhile.

**Comment by bm2u** [comment] 2016-04-13 06:56
Hi folks,

I had the same issue until today. 

Before I got a real solution, I helped myself by copying all svg-source-files via gulp into a temporay folder before generating the iconfont The source filenames do not contain any prepended unicode, so nothing to complain about already used codepoints. The result was as expected - good usable iconfont. The big disadvantage of this procedure was, that with every new added svg-file the internal order of the gylphs were changed continously. Instead of appending the new shape as a glyph, new unicodes were assigned to each source file and rejected the existing unicodes and sort order.

To prevent reordering my glyphs I had to find away, which uses the prepended unicode as fixed identifier and has to assign the next (logical) following unicode to new added files, without resulting naming conflicts. Therefore I added the following lines to my gulp task.

**Extended lines:**
```
gulp.task('iconfont', function(done){

    var lastUnicode = '';
    var iconfontConfig = Object.create(config.options); // Create config object with your options
    var files = fs.readdirSync(config.src).sort(); // Read source directory and sort by name


    // Filter files with containing unicode value
    // and set last unicode
    files.forEach(function(file) {

        var basename = path.basename(file);
        var matches = basename.match(/^(?:((?:u[0-9a-f]{4,6},?)+)\-)?(.+)\.svg$/i);

        if(matches && matches[1]) {
            lastUnicode = matches[1];
        }
    });

    // Cut of the 'u' from unicode value
    // and increase the value with 1
    var getNextUnicode = function(code) {
        var num = parseInt(code.split('u')[1], 16); // convert hex to number
        num++;
        return num;
    };

    ...
    rest of the task to generate font files
    ...
});
```

I hope this will help some of you with this issue. 

@nfroidure This issue takes place as soon as new added filename (without prefixed unicode) begins with a character that comes before 'u' in alphabetical order. If you have filenames like e. g. 'zzWhatEver.svg' everthing works fine. In my point of view the dog is buried in the filter-/ sorting mechanism of the file stream.

**Comment by nfroidure** [comment] 2016-04-13 07:45
@bm2u i'll try to have a look at it but won't probably before 2 weeks.

In the meantime if someone can create a test reproducing the problem probably there if the diag is right:
https://github.com/nfroidure/svgicons2svgfont/blob/master/tests/filesorter.mocha.js

Or maybe there https://github.com/nfroidure/svgicons2svgfont/blob/master/tests/metadata.mocha.js#L193

I'll of course accept the fix too ;).

**Comment by gwildu** [comment] 2016-06-08 15:44
I have the same problem and I think what could fix the problem is to use a capital U when writing the svg files. When I do it manually, it seems to work.

**Comment by nfroidure** [comment] 2017-07-15 12:05
Closing since the problem sit in `svgiconstosvgfont` and no activity sinc ea long time.

**Closed by nfroidure** 2017-07-15 12:05 UTC
Labels: duplicate

**Comment by RyanReese09** [comment] 2017-08-10 13:24
@bm2u could you please post your entire gulp task? 
var iconfontConfig = Object.create(config.options); // Create config object with your options

I'm not sure what that is. I have the same issue with you in regards to the new svg renaming issue. Trying to get that sorted! No other way to contact you so I'm posting here. Please help ASAP :)

**Comment by bm2u** [comment] 2017-08-10 15:00
@RyanReese09 here you are - enjoy!

```
var async = require('async'),
    gulp = require('gulp'),
    iconfont = require('gulp-iconfont'),
    consolidate = require('gulp-consolidate'),
    rename = require('gulp-rename'),
    path = require('path'),
    fs = require('fs'),
    config = require('config/gulp.config').iconfonts;

gulp.task('iconfont:make', function(done){

    var lastUnicode = 0xEA01; //59905

    // Create config object from your presets
    var iconfontConfig = Object.create(config.options);

    // Read source directory and sort by name
    var files = fs.readdirSync('src/images/svg');


    // Filter files with containing unicode value
    // and set last unicode
    files.forEach(function(file) {

        var basename = path.basename(file);
        var matches = basename.match(/^(?:((?:u[0-9a-f]{4,6},?)+)\-)?(.+)\.svg$/i);
        var currentCode = -1;

        if(matches && matches[1]) {
            currentCode = parseInt(matches[1].split('u')[1], 16);
        }

        if(currentCode >= lastUnicode) {
            lastUnicode = ++currentCode;
        }
    });

    // Set startUnicode option to determined unicode from filenames
    iconfontConfig.startUnicode = lastUnicode;

    var iconStream = gulp.src('src/images/**/*.svg')
        .pipe(iconfont(iconfontConfig));

    
    async.parallel([
        // write an CSS file from template
        function handleGlyphs(callback) {
            iconStream.on('glyphs', function(glyphs) {

                var options = {
                    glyphs: glyphs,
                    fontName: 'my-name',
                    fontPath: '../my/path',
                    className: 'my-classname'
                };

                gulp.src('tempates/iconfont.css')
                    .pipe(consolidate('lodash', options))
                    .pipe(rename('my-style.css'))
                    .pipe(gulp.dest('dest/css'))
                    .on('finish', callback);
            });
        },
        // create the iconfont
        function handleFonts(callback) {
            iconStream
                .pipe(gulp.dest('dest/fonts/my-font'))
                .on('finish', callback);
        }
    ], done);
});

```

**Comment by RyanReese09** [comment] 2017-08-10 15:12
@bm2u you're a fantastic human bean. (being) :D . I appreciate this SO SO much. Thank you!

**Comment by RyanReese09** [comment] 2017-08-10 15:16
Last question...what is this composed of?

config = require('config/gulp.config').iconfonts;
var iconfontConfig = Object.create(config.options);

**Comment by bm2u** [comment] 2017-08-10 17:47
@RyanReese09 I got a file inside my `config` directory called `gulp.config.js`.

```
var config = require('config/gulp.config').iconfonts;
```

 Inside this file you would find the following content section:
```
module.exports = {

  iconfonts: {
       src : 'src/images/src',
       options: {
           fontName: 'my-name',
           fontPath: '../my/path',
           className: 'my-classname'
           normalize: true,
           formats: ['ttf', 'eot', 'woff', 'svg'],
           fontHeight: 1024
       }
   }
 
 }
```
During my task I create an object from the entire options-node by:
```
var iconfontConfig = Object.create(config.options);
```
and add the startUnicode property to my last found unicode (after directory scan) from filename by:
```
iconfontConfig.startUnicode = lastUnicode;
```
With that new config-object I'm going to create the iconfont stream.

```
var iconStream = gulp.src('src/images/**/*.svg')
        .pipe(iconfont(iconfontConfig));
```

Hope that helps.

**Comment by RobbertWolfs** [comment] 2019-04-05 07:59
@bm2u  top solution thanks!

**Comment by manjit-jqb** [comment] 2021-07-07 16:50
Hi @bm2u , quick question - what is this template for and where do I get it from? `gulp.src('tempates/iconfont.css')`

Thanks!

**Comment by bm2u** [comment] 2021-07-08 13:36
> Hi @bm2u , quick question - what is this template for and where do I get it from? `gulp.src('tempates/iconfont.css')`
> 
> Thanks!

Hi @manjit-jqb , please refer to the README-section "Usage" and follow the links to relevant examples such as https://github.com/cognitom/symbols-for-sketch/blob/master/templates/fontawesome-style.css
