### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by franktopel** [nfroidure/gulp-iconfont#169] opened 2018-06-20 09:35 UTC
How else am I supposed to know whether it is safe to make a major version upgrade in my project?

**Comment by NaridaL** [comment] 2018-06-20 11:12
Run tests?

For the latest version: gulp-svgicons2svgfont used to cache all the icons
before outputting them so that explicit code points (with prefixedUnicode)
wouldn't clash with automatically generated code points of you mixed
prefixed and non- prefixed icons. The latest version doesn't do that, so
that streaming works properly. If you ARE mixing them, set startUnicode so
that it doesn't overlap the prefixed icons range.

I upgraded the dependency, so gulp-iconfont now has the same limitation.

**Comment by Schweinepriester** [comment] 2021-03-10 11:44
Its been ages, but duplicate of #74.

**Comment by nfroidure** [comment] 2021-03-15 09:31
A changelog is still a good thing but I won't have time to add it that soon. Feel free to PR that said. Would merge if it's done automagically on commit. For an example, see my recenter modules : https://github.com/nfroidure/streamqueue

**Comment by nfroidure** [comment] 2021-03-15 09:32
Closing since duplicate.

**Closed by nfroidure** 2021-03-15 09:32 UTC
