### ISSUE TITLE
Gulp4 - no 'glyphs' event

### ISSUE THREAD

**Issue by daviestar** [nfroidure/gulp-iconfont#98] opened 2015-12-24 13:12 UTC
Hey

Just a heads up - 

I was quickly messing with Gulp4 to see if `gulp.series` could fix some async issues I've been having.  I was able to get the rest of my gulpfile working, but couldn't get the gulp-iconfont task running due to the `glyphs` event not firing.

Cheers.

**Comment by nfroidure** [comment] 2015-12-25 10:38
Hard to tell without an example of the failing code but it looks like custom stream events aren't echoed by `gulp.series`. Worth noting i didn't give a try to Gulp 4 yet, feel free to PR the project or at least create a failing test case in order to reproduce the problem.

**Comment by nfroidure** [comment] 2016-01-14 11:26
Closing since no news.

**Closed by nfroidure** 2016-01-14 11:26 UTC
Labels: invalid, question
